// OOC Chat v1.5.2
import { extension_settings, getContext } from '../../../extensions.js';
import { oai_settings, promptManager } from '../../../openai.js';
import { saveSettingsDebounced } from '../../../../script.js';

const EXT_NAME='OOC_CHAT';
const CONTAINER_ID='ooc-chat-container',ROW_ID='ooc-chat-row',LABEL_ID='ooc-chat-label',INPUT_ID='ooc-chat-input',SEND_ID='ooc-chat-send',COLLAPSE_ID='ooc-chat-collapse',SETTINGS_ID='ooc-chat-settings',POPOVER_ID='ooc-chat-prompt-popover',CLEAR_ID='ooc-chat-prompt-clear';
const PERSONA_STORAGE_KEY='OOC_CHAT_PERSONA_PROMPT';
const defaultSettings={instruction:'Answer in English.',messageColor:'#8fd3ff',showInput:true,promptExclusions:{}};
let settings={},sending=false,eventsBound=false,documentHandlersBound=false,initialized=false,barCollapsed=false,activePopoverTab='exclusions';

function loadSettings(){
    if(!extension_settings[EXT_NAME]) extension_settings[EXT_NAME]={...defaultSettings};
    settings=extension_settings[EXT_NAME];
    if(typeof settings.instruction!=='string') settings.instruction=defaultSettings.instruction;
    if(typeof settings.messageColor!=='string'||!settings.messageColor) settings.messageColor=defaultSettings.messageColor;
    if(typeof settings.showInput!=='boolean') settings.showInput=defaultSettings.showInput;
    if(!settings.promptExclusions||typeof settings.promptExclusions!=='object'||Array.isArray(settings.promptExclusions)) settings.promptExclusions={};
    applyMessageColor();
}
function saveSettings(){extension_settings[EXT_NAME]=settings;saveSettingsDebounced();}
function applyMessageColor(){document.documentElement.style.setProperty('--ooc-chat-message-color',settings.messageColor||defaultSettings.messageColor);}
function applyBarVisibility(){const bar=document.getElementById(CONTAINER_ID);if(!bar)return;bar.hidden=!settings.showInput;if(!settings.showInput)closePromptPopover();}
function setBarCollapsed(v){barCollapsed=Boolean(v);const bar=document.getElementById(CONTAINER_ID),b=document.getElementById(COLLAPSE_ID);if(!bar||!b)return;bar.classList.toggle('ooc-chat-collapsed',barCollapsed);b.setAttribute('aria-expanded',String(!barCollapsed));b.title=barCollapsed?'OOC 입력창 펼치기':'OOC 입력창 접기';const i=b.querySelector('i');if(i)i.className=barCollapsed?'fa-solid fa-chevron-up':'fa-solid fa-chevron-down';if(barCollapsed)closePromptPopover();}
function toast(message,type='info'){const t=window.toastr;if(t&&typeof t[type]==='function')t[type](message,'OOC Chat');else console[type==='error'?'error':'log'](`[OOC Chat] ${message}`);}
function resizeInput(input){if(!input)return;input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,96)}px`;}
function setSendingState(v){sending=v;const i=document.getElementById(INPUT_ID),b=document.getElementById(SEND_ID);if(i)i.disabled=v;if(b){b.disabled=v;b.classList.toggle('ooc-chat-sending',v);b.setAttribute('aria-busy',String(v));}}
async function emitIfAvailable(c,n,id){const t=c?.eventTypes?.[n];if(t&&c?.eventSource?.emit)await c.eventSource.emit(t,id);}
function getInstruction(){return String(settings.instruction??'').trim();}
function normalizeOocInput(text){const trimmed=String(text??'').trim();const match=trimmed.match(/^\(\s*ooc\s*:\s*([\s\S]*?)\s*\)$/i);return match?match[1].trim():trimmed;}
function buildOocMessageText(text,instruction=getInstruction()){const inner=instruction?`${instruction} ${text}`:text;return `(OOC: ${inner})`;}
function buildOocGenerationText(text,instruction,persona){const p=String(persona??'').trim();if(!p)return buildOocMessageText(text,instruction);const request=instruction?`${instruction} ${text}`:text;return `(OOC:\n<OOC_INSTRUCTION>\n${p}\n</OOC_INSTRUCTION>\n\n<OOC_REQUEST>\n${request}\n</OOC_REQUEST>\n)`;}
function getOocDisplayText(m){if(!m?.extra?.ooc_chat)return null;if(typeof m.extra.ooc_display_text==='string')return m.extra.ooc_display_text;const raw=String(m.mes??''),match=raw.match(/^\(ooc:\s*([\s\S]*?)\)$/i);if(!match)return raw;let inner=match[1].trim();const candidates=[typeof m.extra.ooc_instruction==='string'?m.extra.ooc_instruction.trim():'',getInstruction(),defaultSettings.instruction].filter(Boolean);for(const p of candidates){if(inner.toLowerCase().startsWith(p.toLowerCase())){inner=inner.slice(p.length).trimStart();break;}}return inner;}
function decorateOocMessage(messageId){const id=Number(messageId);if(!Number.isInteger(id))return;const c=getContext(),m=c?.chat?.[id];if(!m?.extra?.ooc_chat)return;const el=document.querySelector(`#chat .mes[mesid="${id}"]`),text=el?.querySelector('.mes_text');if(!el||!text)return;const display=getOocDisplayText(m);if(display===null)return;el.classList.add('ooc-chat-message');el.dataset.oocChat='true';if(text.textContent!==display)text.textContent=display;}
function decorateVisibleOocMessages(){const c=getContext();if(!c||!Array.isArray(c.chat))return;document.querySelectorAll('#chat .mes[mesid]').forEach(el=>{const id=Number(el.getAttribute('mesid'));if(Number.isInteger(id)&&c.chat[id]?.extra?.ooc_chat)decorateOocMessage(id);});}
function scheduleVisibleDecoration(){requestAnimationFrame(decorateVisibleOocMessages);setTimeout(decorateVisibleOocMessages,100);}

function getCurrentPresetName(){return String(oai_settings?.preset_settings_openai||'Default');}
function getPresetStorageKey(name=getCurrentPresetName()){return encodeURIComponent(String(name));}
function getExcludedPromptIds(name=getCurrentPresetName()){const v=settings.promptExclusions?.[getPresetStorageKey(name)];return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}
function setPromptExcluded(name,id,excluded){const key=getPresetStorageKey(name),s=new Set(getExcludedPromptIds(name));excluded?s.add(id):s.delete(id);if(s.size)settings.promptExclusions[key]=[...s];else delete settings.promptExclusions[key];saveSettings();}
function clearPromptExclusions(name=getCurrentPresetName()){delete settings.promptExclusions[getPresetStorageKey(name)];saveSettings();renderPromptPopover();requestAnimationFrame(positionPromptPopover);}
function getCurrentPresetPromptEntries(){if(!promptManager||typeof promptManager.getPromptOrderForCharacter!=='function'||typeof promptManager.getPromptById!=='function')return null;try{const order=promptManager.getPromptOrderForCharacter(promptManager.activeCharacter);if(!Array.isArray(order))return[];return order.flatMap((entry,index)=>{if(!entry?.identifier)return[];const p=promptManager.getPromptById(entry.identifier);if(!p||p.marker||p.extension)return[];return[{identifier:String(entry.identifier),name:String(p.name||entry.identifier),role:String(p.role||''),enabled:entry.enabled!==false,index}];});}catch{return null;}}
function getPersonaPrompt(){return String(getContext()?.accountStorage?.getItem(PERSONA_STORAGE_KEY)??'');}
function savePersonaPrompt(value){const s=getContext()?.accountStorage;if(!s)throw new Error('AccountStorage를 사용할 수 없어.');const t=String(value??'').trim();if(t)s.setItem(PERSONA_STORAGE_KEY,t);else s.removeItem(PERSONA_STORAGE_KEY);}
function deletePersonaPrompt(){const s=getContext()?.accountStorage;if(!s)throw new Error('AccountStorage를 사용할 수 없어.');s.removeItem(PERSONA_STORAGE_KEY);}

function ensurePromptPopover(){let p=document.getElementById(POPOVER_ID);if(p)return p;p=document.createElement('div');p.id=POPOVER_ID;p.hidden=true;p.innerHTML=`
<div class="ooc-chat-popover-header"><div class="ooc-chat-popover-heading"><div class="ooc-chat-popover-title">OOC 설정</div><div id="ooc-chat-popover-preset" class="ooc-chat-popover-preset"></div></div><div class="ooc-chat-popover-actions"><button id="${CLEAR_ID}" class="menu_button ooc-chat-prompt-clear" type="button" title="현재 프리셋 체크 모두 해제">전체 해제</button><button id="ooc-chat-popover-close" class="menu_button ooc-chat-popover-close" type="button" title="닫기" aria-label="닫기"><i class="fa-solid fa-xmark"></i></button></div></div>
<div class="ooc-chat-tabs" role="tablist"><button class="ooc-chat-tab" type="button" data-ooc-tab="exclusions" role="tab">프롬프트 제외</button><button class="ooc-chat-tab" type="button" data-ooc-tab="persona" role="tab">OOC 프롬프트</button></div><div id="ooc-chat-popover-body" class="ooc-chat-popover-body"></div>`;document.body.appendChild(p);p.querySelector('#ooc-chat-popover-close')?.addEventListener('click',closePromptPopover);p.querySelector(`#${CLEAR_ID}`)?.addEventListener('click',()=>clearPromptExclusions());p.querySelectorAll('[data-ooc-tab]').forEach(b=>b.addEventListener('click',()=>{activePopoverTab=b.dataset.oocTab==='persona'?'persona':'exclusions';renderPromptPopover();requestAnimationFrame(positionPromptPopover);}));return p;}
function renderPromptPopover(){const p=ensurePromptPopover(),name=getCurrentPresetName(),preset=p.querySelector('#ooc-chat-popover-preset'),body=p.querySelector('#ooc-chat-popover-body'),clear=p.querySelector(`#${CLEAR_ID}`);if(!preset||!body)return;p.querySelectorAll('[data-ooc-tab]').forEach(b=>{const on=b.dataset.oocTab===activePopoverTab;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});if(activePopoverTab==='persona'){preset.textContent='모든 프리셋 공통 · AccountStorage';if(clear)clear.hidden=true;renderPersonaTab(body);}else{preset.textContent=`현재 프리셋: ${name}`;if(clear)clear.hidden=false;renderExclusionsTab(body,name,clear);}}
function renderExclusionsTab(body,name,clear){body.replaceChildren();const list=document.createElement('div');list.className='ooc-chat-prompt-list';const entries=getCurrentPresetPromptEntries(),selected=new Set(getExcludedPromptIds(name));if(clear)clear.disabled=selected.size===0;if(entries===null||entries.length===0){const m=document.createElement('div');m.className='ooc-chat-prompt-empty';m.textContent=entries===null?'Prompt Manager를 아직 읽을 수 없어. 잠시 후 다시 열어줘.':'현재 프리셋에서 선택할 수 있는 프롬프트가 없어.';list.appendChild(m);}else for(const e of entries){const label=document.createElement('label');label.className='ooc-chat-prompt-item';const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.has(e.identifier);cb.dataset.promptIdentifier=e.identifier;cb.addEventListener('change',()=>{setPromptExcluded(name,e.identifier,cb.checked);if(clear)clear.disabled=getExcludedPromptIds(name).length===0;});const text=document.createElement('span');text.className='ooc-chat-prompt-item-text';const n=document.createElement('span');n.className='ooc-chat-prompt-name';n.textContent=e.name;const meta=document.createElement('span');meta.className='ooc-chat-prompt-meta';meta.textContent=[e.role,!e.enabled?'현재 OFF':''].filter(Boolean).join(' · ');text.appendChild(n);if(meta.textContent)text.appendChild(meta);label.append(cb,text);list.appendChild(label);}const note=document.createElement('div');note.className='ooc-chat-popover-note';note.textContent='체크한 프롬프트는 이 프리셋에서 OOC로 보낼 때만 제외돼. 선택은 즉시 저장돼.';body.append(list,note);}
function renderPersonaTab(body){body.replaceChildren();const wrap=document.createElement('div');wrap.className='ooc-chat-persona-pane';const ta=document.createElement('textarea');ta.id='ooc-chat-persona-input';ta.className='text_pole ooc-chat-persona-input';ta.rows=10;ta.placeholder='OOC에서만 사용할 인격/작동 프롬프트를 입력해. 비워두면 추가 프롬프트를 주입하지 않아.';ta.value=getPersonaPrompt();const status=document.createElement('div');status.className='ooc-chat-persona-status';status.textContent=ta.value?'저장된 OOC 프롬프트가 있어.':'저장된 OOC 프롬프트가 없어.';const actions=document.createElement('div');actions.className='ooc-chat-persona-actions';const save=document.createElement('button');save.className='menu_button';save.type='button';save.textContent='저장';const del=document.createElement('button');del.className='menu_button ooc-chat-persona-delete';del.type='button';del.textContent='삭제';del.disabled=!ta.value;save.addEventListener('click',()=>{try{savePersonaPrompt(ta.value);ta.value=getPersonaPrompt();const exists=Boolean(ta.value);status.textContent=exists?'저장됨.':'비어 있어서 저장 항목을 삭제했어.';del.disabled=!exists;}catch(e){console.error('[OOC Chat] Failed to save persona prompt:',e);toast(`OOC 프롬프트 저장 오류: ${e?.message||e}`,'error');}});del.addEventListener('click',()=>{try{deletePersonaPrompt();ta.value='';status.textContent='삭제됨.';del.disabled=true;}catch(e){console.error('[OOC Chat] Failed to delete persona prompt:',e);toast(`OOC 프롬프트 삭제 오류: ${e?.message||e}`,'error');}});ta.addEventListener('input',()=>status.textContent='저장되지 않은 변경사항이 있어.');actions.append(save,del);const note=document.createElement('div');note.className='ooc-chat-popover-note';note.textContent='이 프롬프트는 계정 저장소에 보관되고, OOC 전송 때 최신 user 입력의 <OOC_INSTRUCTION> 블록으로만 임시 결합돼. 빈 상태로 저장하거나 삭제를 누르면 저장 키 자체가 제거돼.';wrap.append(ta,status,actions,note);body.appendChild(wrap);}
function positionPromptPopover(){const p=document.getElementById(POPOVER_ID),label=document.getElementById(LABEL_ID);if(!p||p.hidden||!label)return;const r=label.getBoundingClientRect(),m=8,g=6,w=p.offsetWidth,h=p.offsetHeight;let left=Math.max(m,Math.min(r.left,window.innerWidth-w-m)),top=r.top-h-g;if(top<m)top=r.bottom+g;top=Math.max(m,Math.min(top,window.innerHeight-h-m));p.style.left=`${Math.round(left)}px`;p.style.top=`${Math.round(top)}px`;}
function openPromptPopover(){if(barCollapsed)return;const p=ensurePromptPopover();renderPromptPopover();p.hidden=false;requestAnimationFrame(positionPromptPopover);}
function closePromptPopover(){const p=document.getElementById(POPOVER_ID);if(p)p.hidden=true;}
function togglePromptPopover(){const p=ensurePromptPopover();p.hidden?openPromptPopover():closePromptPopover();}
function applyPromptExclusionsForCurrentGeneration(){const ids=getExcludedPromptIds();if(!ids.length)return()=>{};if(!promptManager||typeof promptManager.getPromptOrderEntry!=='function')throw new Error('Prompt Manager를 사용할 수 없어 OOC 프롬프트 제외를 적용할 수 없어.');const states=[];for(const id of ids){const e=promptManager.getPromptOrderEntry(promptManager.activeCharacter,id);if(!e)continue;states.push({entry:e,enabled:e.enabled});e.enabled=false;}return()=>{for(const s of states)s.entry.enabled=s.enabled;};}

async function sendOocMessage(){
    if(sending)return;const input=document.getElementById(INPUT_ID);if(!input)return;const text=normalizeOocInput(input.value);if(!text)return;
    const c=getContext();if(!c||!Array.isArray(c.chat)){toast('현재 채팅을 찾을 수 없어.','error');return;}
    const hasChar=c.characterId!==undefined&&c.characterId!==null,hasGroup=c.groupId!==undefined&&c.groupId!==null&&c.groupId!=='';if(!hasChar&&!hasGroup){toast('먼저 캐릭터나 그룹 채팅을 열어줘.','warning');return;}
    const instruction=getInstruction(),storedText=buildOocMessageText(text,instruction),message={name:c.name1,is_user:true,is_system:false,send_date:new Date().toISOString(),mes:storedText,extra:{ooc_chat:true,ooc_instruction:instruction}};
    setSendingState(true);closePromptPopover();let restorePromptStates=()=>{},generationMessage=null;
    try{
        restorePromptStates=applyPromptExclusionsForCurrentGeneration();
        c.chat.push(message);const messageId=c.chat.length-1;
        await emitIfAvailable(c,'MESSAGE_SENT',messageId);c.addOneMessage(message);await emitIfAvailable(c,'USER_MESSAGE_RENDERED',messageId);await c.saveChat();decorateOocMessage(messageId);
        input.value='';resizeInput(input);c.scrollChatToBottom?.();
        const persona=String(c?.accountStorage?.getItem(PERSONA_STORAGE_KEY)??'').trim();generationMessage=c.chat[messageId];if(generationMessage&&persona)generationMessage.mes=buildOocGenerationText(text,instruction,persona);
        await c.executeSlashCommandsWithOptions('/trigger await=true',{handleParserErrors:true,handleExecutionErrors:true});
    }catch(e){console.error('[OOC Chat] Failed to send OOC message:',e);toast(`OOC 전송 오류: ${e?.message||e}`,'error');}
    finally{if(generationMessage)generationMessage.mes=storedText;restorePromptStates();setSendingState(false);if(!barCollapsed&&settings.showInput)input.focus();}
}

function buildBar(){const c=document.createElement('div');c.id=CONTAINER_ID;c.innerHTML=`<div id="${ROW_ID}" class="ooc-chat-row"><button id="${LABEL_ID}" class="ooc-chat-label" type="button" title="OOC 설정" aria-label="OOC 설정">OOC</button><textarea id="${INPUT_ID}" class="text_pole" rows="1" spellcheck="true" autocomplete="off" placeholder="OOC question..." aria-label="OOC message input"></textarea><button id="${SEND_ID}" class="menu_button" type="button" title="Send OOC message" aria-label="Send OOC message"><i class="fa-solid fa-paper-plane"></i></button></div><button id="${COLLAPSE_ID}" class="ooc-chat-collapse" type="button" title="OOC 입력창 접기" aria-label="OOC 입력창 접기" aria-expanded="true"><i class="fa-solid fa-chevron-down"></i></button>`;const input=c.querySelector(`#${INPUT_ID}`),send=c.querySelector(`#${SEND_ID}`),label=c.querySelector(`#${LABEL_ID}`),collapse=c.querySelector(`#${COLLAPSE_ID}`);input.addEventListener('input',()=>resizeInput(input));input.addEventListener('keydown',e=>{if(e.isComposing||e.keyCode===229)return;if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendOocMessage();}});send.addEventListener('click',sendOocMessage);label.addEventListener('click',togglePromptPopover);collapse.addEventListener('click',()=>setBarCollapsed(!barCollapsed));return c;}
function findSettingsRoot(){return document.getElementById('extensions_settings2')||document.getElementById('extensions_settings');}
function injectSettingsPanel(){if(document.getElementById(SETTINGS_ID))return true;const root=findSettingsRoot();if(!root)return false;const p=document.createElement('div');p.id=SETTINGS_ID;p.className='extension_container';p.innerHTML=`<div class="inline-drawer"><div class="inline-drawer-toggle inline-drawer-header"><b>OOC Chat</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down interactable" tabindex="0"></div></div><div class="inline-drawer-content ooc-chat-settings-content"><label class="checkbox_label" for="ooc-chat-show-input"><input id="ooc-chat-show-input" type="checkbox" /><span>OOC 입력창 보이기</span></label><label for="ooc-chat-instruction">OOC 뒤 고정 문구</label><textarea id="ooc-chat-instruction" class="text_pole" rows="2" placeholder="예: Answer in English."></textarea><small>모델에는 (OOC: [이 문구] [입력 내용]) 형태로 전달돼. 비워두면 (OOC: [입력 내용])만 전달돼.</small><label for="ooc-chat-color">OOC 메시지 글자색</label><div class="ooc-chat-color-row"><input id="ooc-chat-color" type="color" /><span id="ooc-chat-color-value"></span></div><small>입력창 왼쪽 OOC 버튼에서 프리셋별 제외 프롬프트와 공통 OOC 프롬프트를 설정할 수 있어.</small><button id="ooc-chat-settings-save" class="menu_button" type="button">저장</button></div></div>`;root.appendChild(p);const show=p.querySelector('#ooc-chat-show-input'),instruction=p.querySelector('#ooc-chat-instruction'),color=p.querySelector('#ooc-chat-color'),value=p.querySelector('#ooc-chat-color-value'),save=p.querySelector('#ooc-chat-settings-save');show.checked=settings.showInput;instruction.value=settings.instruction;color.value=settings.messageColor;value.textContent=settings.messageColor;show.addEventListener('change',()=>{settings.showInput=show.checked;applyBarVisibility();saveSettings();});color.addEventListener('input',()=>{value.textContent=color.value;document.documentElement.style.setProperty('--ooc-chat-message-color',color.value);});save.addEventListener('click',()=>{settings.showInput=show.checked;settings.instruction=instruction.value.trim();settings.messageColor=color.value;applyBarVisibility();applyMessageColor();saveSettings();scheduleVisibleDecoration();toast('설정을 저장했어.','success');});return true;}
function ensureOocBar(){let bar=document.getElementById(CONTAINER_ID);if(!bar){const form=document.getElementById('send_form');if(!form?.parentElement)return false;bar=buildBar();form.parentElement.insertBefore(bar,form);setBarCollapsed(barCollapsed);}applyBarVisibility();return true;}
function ensureUi(){ensureOocBar();injectSettingsPanel();}
function scheduleUiBootstrap(){[0,250,1000,2500,5000].forEach(d=>setTimeout(ensureUi,d));}
function bindDocumentHandlers(){if(documentHandlersBound)return;documentHandlersBound=true;document.addEventListener('pointerdown',e=>{const p=document.getElementById(POPOVER_ID);if(!p||p.hidden)return;const l=document.getElementById(LABEL_ID);if(p.contains(e.target)||l?.contains(e.target))return;closePromptPopover();},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')closePromptPopover();});window.addEventListener('resize',()=>{const p=document.getElementById(POPOVER_ID);if(p&&!p.hidden)positionPromptPopover();});}
function bindEvents(){if(eventsBound)return;const c=getContext(),es=c?.eventSource,et=c?.eventTypes;if(!es||!et)return;if(et.APP_READY)es.on(et.APP_READY,()=>{ensureUi();scheduleVisibleDecoration();});if(et.CHAT_CHANGED)es.on(et.CHAT_CHANGED,()=>{ensureOocBar();closePromptPopover();scheduleVisibleDecoration();});if(et.OAI_PRESET_CHANGED_AFTER)es.on(et.OAI_PRESET_CHANGED_AFTER,()=>{const p=document.getElementById(POPOVER_ID);if(p&&!p.hidden){renderPromptPopover();requestAnimationFrame(positionPromptPopover);}});if(et.USER_MESSAGE_RENDERED)es.on(et.USER_MESSAGE_RENDERED,id=>decorateOocMessage(id));if(et.MESSAGE_EDITED)es.on(et.MESSAGE_EDITED,id=>setTimeout(()=>decorateOocMessage(id),0));eventsBound=true;}
async function initOocChat(){if(initialized)return;initialized=true;loadSettings();bindEvents();bindDocumentHandlers();ensureUi();scheduleUiBootstrap();scheduleVisibleDecoration();console.log('[OOC Chat] v1.5.2 loaded');}
export async function init(){await initOocChat();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initOocChat,{once:true});else initOocChat();
